name: Packer Practice Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
      
      - name: Packer Init
        run : "packer init aws-ubuntu.pkr.hcl"
      
      - name: Packer Validate
        run : "packer validate aws-ubuntu.pkr.hcl"

      - name: Packer Build
        run : "packer build aws-ubuntu.pkr.hcl"
            
